name: lotus
version: 1.0.0
config-version: 2

profile: lotus

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS {{ target.catalog }}.core"
  - "CREATE SCHEMA IF NOT EXISTS {{ target.catalog }}.mart"

models:
  lotus:  
    core:
      +materialized: incremental
      +incremental_strategy: delete+insert
      +on_schema_change: 'sync_all_columns'
    mart:
      +materialized: table
      +schema: mart