version: 2

models:
  - name: shopify_orders
    description: "Cleaned Shopify orders with totals, customer info, and shipping details."
    columns:
      - name: order_id
        description: "Unique Shopify order ID"
        meta:
          dimension: { type: string }

      - name: order_name
        description: "Order name or display number"
        meta:
          dimension: { type: string }

      - name: created_at
        description: "Timestamp when the order was created"
        meta:
          dimension: { type: timestamp }

      - name: updated_at
        description: "Timestamp when the order was last updated"
        meta:
          dimension: { type: timestamp }

      - name: financial_status
        description: "Shopify display financial status (e.g. paid, partially_refunded)"
        meta:
          dimension: { type: string }

      - name: subtotal
        description: "Order subtotal before discounts"
        meta:
          dimension: { type: number }
          metrics:
            total_subtotal: { type: sum }
            avg_subtotal: { type: average }

      - name: discounts_total
        description: "Total discounts applied across the order"
        meta:
          dimension: { type: number }
          metrics:
            total_discounts: { type: sum }

      - name: total_tax
        description: "Total tax charged on the order"
        meta:
          dimension: { type: number }
          metrics:
            total_tax_collected: { type: sum }

      - name: total_price
        description: "Final total including discounts, tax, and shipping"
        meta:
          dimension: { type: number }
          metrics:
            total_revenue: { type: sum }
            avg_order_value: { type: average }

      - name: shipping_cost
        description: "Shipping charges applied to the order"
        meta:
          dimension: { type: number }
          metrics:
            total_shipping: { type: sum }

      - name: channel_name
        description: "Sales channel name (e.g. Online Store, POS, Faire)"
        meta:
          dimension: { type: string }

      - name: customer_id
        description: "Unique Shopify customer ID"
        meta:
          dimension: { type: string }

      - name: customer_email
        description: "Customer email address"
        meta:
          dimension: { type: string }

      - name: shipping_city
        description: "City from shipping address"
        meta:
          dimension: { type: string }

      - name: shipping_country_code
        description: "Two-letter shipping country code"
        meta:
          dimension: { type: string }

  - name: shopify_order_lines
    description: "Flattened line items for each Shopify order"
    columns:
      - name: line_item_id
        description: "Unique line item identifier"
        meta:
          dimension: { type: string }

      - name: order_id
        description: "Parent order ID"
        meta:
          dimension: { type: string }

      - name: title
        description: "Product title"
        meta:
          dimension: { type: string }

      - name: sku
        description: "SKU of the variant"
        meta:
          dimension: { type: string }

      - name: quantity
        description: "Quantity ordered"
        meta:
          dimension: { type: number }
          metrics:
            total_quantity: { type: sum }

      - name: product_type
        description: "Product category or type"
        meta:
          dimension: { type: string }

      - name: variant_price
        description: "Variant base price"
        meta:
          dimension: { type: number }

      - name: discounted_total
        description: "Final line item total after discounts"
        meta:
          dimension: { type: number }
          metrics:
            line_revenue: { type: sum }

  - name: shopify_discounts
    description: "Detailed discount applications, including order- and line-level breakdowns."
    columns:
      - name: discount_id
        description: "Surrogate key for unique discount instance"
        meta:
          dimension: { type: string }

      - name: order_id
        description: "Associated order ID"
        meta:
          dimension: { type: string }

      - name: line_item_id
        description: "Associated line item (if applicable)"
        meta:
          dimension: { type: string }

      - name: discount_code
        description: "Discount or promo code applied"
        meta:
          dimension: { type: string }

      - name: discount_index
        description: "Shopify-internal index for identifying distinct discounts per order"
        meta:
          dimension: { type: number }

      - name: discount_type
        description: "Shopify discount type (e.g. DiscountCodeApplication)"
        meta:
          dimension: { type: string }

      - name: allocation_method
        description: "How the discount is distributed (e.g. across line items or per order)"
        meta:
          dimension: { type: string }

      - name: target_selection
        description: "What the discount targets (entire order, specific items)"
        meta:
          dimension: { type: string }

      - name: discount_value
        description: "Discount value (percentage or fixed amount)"
        meta:
          dimension: { type: number }
          metrics:
            total_discount_value: { type: sum }

      - name: allocated_amount
        description: "Monetary value allocated to this line/item"
        meta:
          dimension: { type: number }
          metrics:
            total_allocated_discount: { type: sum }

  - name: shopify_tax_lines
    description: "Tax line breakdowns per order or shipping line"
    columns:
      - name: order_id
        description: "Associated order ID"
        meta:
          dimension: { type: string }

      - name: tax_type
        description: "Tax name or jurisdiction"
        meta:
          dimension: { type: string }

      - name: amount
        description: "Tax amount in shop currency"
        meta:
          dimension: { type: number }
          metrics:
            total_tax: { type: sum }
