FROM lotus-spark-base:latest

ENV SPARK_MODE=master \
    SPARK_MASTER_HOST=spark-master \
    SPARK_MASTER_PORT=7077 \
    SPARK_MASTER_WEBUI_PORT=8080

EXPOSE 7077 8080 6066

CMD ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", \
     "--host", "0.0.0.0", "--port", "7077", "--webui-port", "8080"]
