name: 'lotus_lake'
version: '1.0.0'

profile: 'lotus_lake'

model-paths: ["assets/core/shopify", "assets/core/klaviyo", "assets/marts/sales"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Write all models to DuckLake (lakehouse database)
models:
  lotus_lake:
    +database: lakehouse
    +schema: main
