name: 'lotus_lake'
version: '1.0.0'

profile: 'lotus_lake'

model-paths: ["dag/processed/shopify", "dag/processed/klaviyo", "dag/processed/odoo", "dag/enriched/sales"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Write all models to DuckLake (lakehouse database)
# DuckLake default schema is 'main', so don't set +schema to avoid 'main_main'
models:
  lotus_lake:
    +database: lakehouse
