"""
Dagster Resources

Central module for all Dagster resources and shared constants.
"""
from pathlib import Path

from dagster_dbt import DbtCliResource

# dbt manifest path (generated by `dbt parse` or `dbt run`)
DBT_MANIFEST = Path(__file__).parent / "target" / "manifest.json"

# dbt resource
dbt_resource = DbtCliResource(
    project_dir=Path(__file__).parent,
    profiles_dir=Path(__file__).parent,
)

__all__ = [
    "dbt_resource",
    "DBT_MANIFEST",
]
